# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew test
      - run:
          name: Assemble
          command: ./gradlew assemble
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      - store_test_results:
          path: app/build/test-results
      - deploy:
          name: Release Github
          command: |
            if [ -n "${CIRCLE_TAG}" ]; then
              body=$(git tag -n --sort=-taggerdate --points-at HEAD --format='%(contents)')
              ORG_GRADLE_PROJECT_TAG_VERSION="${CIRCLE_TAG}" ./gradlew -PreleaseBody="${body}" githubRelease
            fi
deployment:
  deploy:
    tag: /.*/
    command: |
      echo "CIRCLE_BRANCH: ${CIRCLE_BRANCH}, CIRCLE_TAG: ${CIRCLE_TAG}."